# Generated by Django 4.2.24 on 2025-10-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('180ml', '180ml'), ('500ml', '500ml')], default='180ml', null=True),
        ),
    ]
