# Generated by Django 4.2.24 on 2025-10-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_candle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
